$(document).ready(function(){
    $(".all").click(function(){
        $("#p1").toggle();
        $("#img1").toggle();
    });
});
$(document).ready(function(){
    $(".all").click(function(){
        $("#p1").toggle();
        $("#img1").toggle();
    });
});